### ISSUE TITLE
Undefined behaviour for data races

### ISSUE THREAD

**Issue by aviansie-ben** [qbicc/qbicc#516]
After some perusing of the LLVM documentation, I've found out that LLVM's memory model considers regular loads and stores with data races to return an undefined result [1]. Because of this, it's perfectly possible for LLVM to perform optimizations such as repeating a load rather than using spill slots on the stack when running out of registers under certain conditions, storing incorrect intermediate results temporarily over the target of a store, or speculatively performing a load that does not alias any stores from the current thread early.

From what I can see in the documentation, it is necessary for us to use atomics with an ordering of `Unordered` for all field/array loads and stores to get correct Java semantics in the presence of multiple threads. This seems to have relatively low overhead and only guarantees that data races get somewhat sane results. It does inhibit the optimizer slightly, but that seems to be necessary for correctness.

This does bring up one very big question though: what is QBICC's memory model for reading/writing via C pointers? Should a data race caused by using pointers produce an undefined result or should it act the same as a data race on a Java field?

[1] https://llvm.org/docs/Atomics.html#notatomic

**Comment by dmlloyd** [comment]
Thanks @theRealAph.  We actually are not generating a `RELEASE` fence after constructor invocation and we ought to be.  Assuming that gets fixed though, using a `NONE` (C plain/non-atomic) access on header fields is not good enough (at least, by my understanding of the LLVM [definition of `unordered`](https://llvm.org/docs/Atomics.html#unordered) that I'm gleaning from the docs).  The LLVM memory model does not appear to guarantee that a `RELEASE` will make non-atomic updates visible, where "atomic" is defined (for our purposes) as `UNORDERED` or higher.

**Comment by theRealAph** [comment]
On 5/20/21 4:53 PM, David M. Lloyd wrote:

> using a `NONE` (C plain/non-atomic) access on header fields is not good enough (at least, by my understanding of the LLVM [definition of `unordered`](https://llvm.org/docs/Atomics.html#unordered) that I'm gleaning from the docs).  The LLVM memory model does not appear to guarantee that a `RELEASE` will make non-atomic updates visible, where "atomic" is defined (for our purposes) as `UNORDERED` or higher.

That's right, it's not. This is a pretty fundamental difference between C++
and Java, and you need (at least) memory_order_consume on the reading
side. Trouble is, consume isn't implemented as anything other than acquire
on any compiler I know. You can probably get away with "Monotonic" if you use
it for all field loads on x86 and AArch64, but that's not strictly correct.

-- 
Andrew Haley  (he/him)
Java Platform Lead Engineer
Red Hat UK Ltd. <https://www.redhat.com>
https://keybase.io/andrewhaley
EAC8 43EB D3EF DB98 CC77 2FAD A5CD 6035 332F A671

**Comment by dmlloyd** [comment]
The LLVM docs do specifically indicate that `unordered` is meant to work as the normal access mode for Java shared variables.  They also specify `seq_cst` as being specifically suitable for Java volatiles, but they also define it specifically in terms of `acquire` and `release`.  So it seems that either the docs must be wrong due to a misunderstanding of the JMM, or else their `acquire`/`release` (at least when employed as a fence rather than a single-value atomic access) must also suffice to cover `unordered` variables (which at any rate do not have a C/C++ MM equivalent).  I guess I will ask on the `llvm-dev` mailing list, unless you see a glaring hole in my thinking (which is a very real possibility, if we're being honest).

**Comment by theRealAph** [comment]
On 5/21/21 4:03 PM, David M. Lloyd wrote:

> The LLVM docs do specifically indicate that `unordered` is meant to
> work as the normal access mode for Java shared variables.  They also
> specify `seq_cst` as being specifically suitable for Java volatiles,
> but they also define `seq_cst` specifically in terms of `acquire`
> and `release`.

seq_cst is defined by the C/C++ language standard, so I'd hope that
the standard definition would win.

> So it seems that either the docs must be wrong due to a
> misunderstanding of the JMM, or else their `acquire`/`release` (at
> least when employed as a fence rather than a single-value atomic
> access) must also suffice to cover `unordered` variables (which at
> any rate do not have a C/C++ MM equivalent).  I guess I will ask on
> the `llvm-dev` mailing list, unless you see a glaring hole in my
> thinking (which is a very real possibility, if we're being honest).

Hard to say if they understand the JMM or not, but the details of
getting this right are very subtle.

Here's the tricky part: for causal ordering to work, you have to be
sure that you use a pointer that has the right dependency chain.

Say in Thread 1, you do this in a constructor:

(all global state is initially null, all locals are zero, unless
otherwise stated.)

r1->bar = 77;
StoreStore;
foo = r1;

And in Thread 2, you do this:

r2 = foo;
r3 = foo->bar;  // unordered load

So, is r3 guaranteed to be 77? Yes, on most machines, because there's
a StoreStore fence in the writer and an address dependency in the
reader. But what if the compiler knows that some other pointer X is
equal to foo and uses X-> bar instead? Then all bets are off.

Can something like that happen in Java? I don't think it can, without
unsafe publication. So I think you're OK, but I'm not entirely
comfortable with that. But there may b similar scenarios with, for
example, concurrent GCs.

[ NB: there's nothing in the C++ memory model that guarantees address
dependencies are respected, that's a property of the hardware the code
is running on. ]

So, if LLVM wants unordered to be adequate for Java fields, they really
need to say something about address dependencies.

For your, er, amusement, see the nightmare "Rules for 2014 GCC
Implementations" in
http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2015/p0098r0.pdf

-- 
Andrew Haley  (he/him)
Java Platform Lead Engineer
Red Hat UK Ltd. <https://www.redhat.com>
https://keybase.io/andrewhaley
EAC8 43EB D3EF DB98 CC77 2FAD A5CD 6035 332F A671
