### ISSUE TITLE
ServiceLoader support

### ISSUE THREAD

**Issue by theresa-m** [qbicc/qbicc#544]
Prior to recent rebases I was facing the following issue which I think is due to a lack of service provider support:
```
LoggerWrapper.java: error: Missing method implementation for vtable of jdk/internal/logger/LoggerWrapper
    member: method log
  location: type LoggerWrapper
LoggerWrapper.java: error: Missing method implementation for vtable of jdk/internal/logger/LoggerWrapper
    member: method isLoggable
  location: type LoggerWrapper
LoggerWrapper.java: error: Missing method implementation for vtable of jdk/internal/logger/LoggerWrapper
    member: method log
  location: type LoggerWrapper
LoggerWrapper.java: error: Missing method implementation for vtable of jdk/internal/logger/LoggerWrapper
    member: method log
  location: type LoggerWrapper
Compilation failed with 4 error(s) and 1549 warning(s)
```
Unfortunately w/recent changes I am not able to reproduce this often anymore.

I am thinking of:
1. creating a test case to help me reproduce a similar error again, where a default service implementation is being filtered out of the allowed classes
2. Start out with something similar to Jarmin's approach [1] and identify service interfaces using `ServiceLoader.load` and add classes that provide an implementation to the allowed set of classes

Another way of making this easier once we're dealing with multiple modules could be to take advantage of module-info files that should list any implementations outside of the module using the service.

[1] https://github.com/eclipse-openj9/openj9-utils/blob/9e3e4aa179a946dbb97f974496248e2d41db5224/jarmin/src/org/eclipse/openj9/jmin/analysis/ReferenceAnalyzer.java#L193

**Comment by dmlloyd** [comment]
I suspect this is caused by the same issue that @dgrove-oss is looking into: separating the reachability of classes that are actually instantiated vs merely referenced.  @DanHeidinga's recent class init change causes more subtypes to be reachable, thus this probably hides the problem.  But I think once the RTA stuff is updated, this problem might disappear for good.

On the topic of `ServiceLoader` I think we want to go one step farther: any case where a service loader is called, we should return a service loader using a fixed iterator that directly instantiates the service implementations for that class.  For cases where the service class is constant or can be derived as a constant, we can directly return the corresponding fixed-iterator service loader; for other cases we can use a map lookup and our existing type analysis to determine which one to return.

Prior thoughts on this topic: [this Quarkus issue](https://github.com/quarkusio/quarkus/pull/1846#issuecomment-479671999)

**Comment by DanHeidinga** [comment]
If we need to generate code for the fixed iterator, there's a quarkus project that may help - https://github.com/quarkusio/gizmo

An example of it's use is https://github.com/mkouba/gizmo-insights/blob/main/gizmonster/deployment/src/main/java/org/acme/gizmonster/deployment/GizmonsterProcessor.java

**Comment by dgrove-oss** [comment]
Dealing with ServiceLoaders (at least those configured via provider-configuration files) is now a blocking issue for running Quarkus.  So, I'm going to take a cut at implementing at least that aspect of it.  The sketch of the plan is:
1. Define an ADD PreHook to process the entire class path and find all provider-configuration files.  Parse each of these files and create a `<String, <List<String>>>` mapping from services to service providers.
2. Extend reachability analysis so that when a service becomes reachable, we make all the providers reachable (this includes making their constructors available for runtime reflection).  Keep track of reachable services.  Just like everything else in Reachability analysis, this can be cleared and re-computed in the ANALYZE phase for increased prevision.
3. Extend the heap serialization process to also write a data structure that maps service Class objects to Class[] of providers using the final reachability results after the ANALYZE phase.
4. Write our own ServiceLoader implementation that uses this initial heap data structure to implement runtime ServiceLoader operations.
5. Have build-time invokables for ServiceLoader that use the reachability data structures to allow for build-time execution of ServiceLoader operations.
