### ISSUE TITLE
Introduce a trace engine / flight recorder style VM specific logging system

### ISSUE THREAD

**Issue by DanHeidinga** [qbicc/qbicc#550]
Generating logging data to trace important application events makes a system much easier to debug and reason about when the behaviour of the application is unexpected or to diagnose the causes of crashes.

OpenJ9 has a trace engine that outputs low level VM events that can be used to determine the last few operations on the thread (by default) or redirected to a file to trace the full operation.  

OpenJDK has JFR which I understand serves a similar purpose and allows for profiling of the application as well.

Qbicc needs something like this as we have increasingly large applications to debug and it can be difficult to recreate the semantics of an operation after it has been optimized.

Proposal
--

Introduce a minimal trace engine into qbicc as a short term step.  This can be used to print information (trace points) at relevant operations, like during class initialization, many VMHelpers, etc.

Tracepoints must always include:
* timestamp
* current thread id
* level specifier
* user specified data.

Tracepoints should be off by default and should be enabled by a `--enable-vm-trace` command line when building an application with qbicc.  This option will control whether a `QbiccTrace::isEnabled()` method returns true/false at build time.

All operations involved in trace should be in java code snippets such as:
```java
if (QbiccTrace.isEnabled()) {
   QbiccTrace.trace(level, "user supplied data");
}
```
so that we can DCE it when trace is not enabled.

Our eventual goal should be to evaluate whether qbicc can generate JFR events and use the pre-existing tools to support these low-level monitoring concerns.

**Comment by galderz** [comment]
The pattern suggested above was heavily used in Infinispan, where I worked since it's inception for about 10 years. I would often enable trace when debugging something, but I would often find myself wondering: oh, I wished the trace logging included that piece of data that it doesn't currently log, or I wished there was a trace message in that particular location. The log messages baked in the code can be semi-aleatory, meaning that the person who adds them thinks it'll help tracing, but often when an issue arises, you'd like to have something slightly different.

Moreover, enabling trace logging can result in huge files that you then have to grep for the relevant information. In the case of qbicc, I've already found myself wanting to see what BBB callbacks I get for a particular method compilation. With the proposed suggestion above, I would have to enable trace logging globally, then grep to see where my method compilation starts, figure out the thread name, then grep/pipe only the info from that thread somewhere for closer inspection. This is a pain.

I'd like to propose an alternative way to do trace logging. 

Originally it was inspired by listening to Martin Thompson explain [how Aeron does trace logging](https://aeroncookbook.com/aeron/aeron-agent/#:~:text=Aeron%20Agent%20is%20a%20Java,high%20volume%20data%20frame%20events.). In essence, they use an custom made agent that they hook onto Aeron to log very low level details. The nice thing about this approach is that you don't need to litter your production code with `if (trace.enabled) { ... }` like messages. IMO, these pieces of code distract from what the code does. Also, you have to hope that DCE will (eventually) remove that...

I think we can do even better than Aeron actually by taking advantage of the homegrown [Byteman](https://byteman.jboss.org/), created by @adinn many moons ago. Similar to Aeron, Byteman also uses an agent to hook into the VM, but it's a more flexible tool where the user defines the rules to bind to and then decide what action to take, for example: log a message.

I've already been experimenting with this within the scope of the EA work I'm doing. The latest Byteman rules I'm using can be found [here](https://github.com/galderz/qoccido/blob/main/ea-04/logging.btm), but aside from binding to a method and logging something, you can bind in more complex ways. For example:

```
RULE set up ea bbb
CLASS EscapeAnalysisBasicBlockBuilder
METHOD <init>
AT EXIT
IF $2.getCurrentElement().toString().contains("first")
DO
  link("threadName", Thread.currentThread().getName());
  traceln("(" + Thread.currentThread().getName() + ") construct EscapeAnalysisBBB for " + $2.getCurrentElement().toString())
ENDRULE
...
RULE ea bbb new
CLASS DelegatingBasicBlockBuilder
METHOD new_
AT EXIT
BIND
  isEA = org.qbicc.plugin.opt.EscapeAnalysisBasicBlockBuilder.class.isInstance($this);
  threadName = linked("threadName");
IF
  isEA
  AND
  Thread.currentThread().getName().equals(threadName)
DO
  traceln("(" + Thread.currentThread().getName() + ") exit new_(" + $1.toString() + ") with " + $!);
ENDRULE
```

The aboves rules say: when `EscapeAnalysisBasicBlockBuilder` is created for method `first`, capture the thread name that calls it. Then, when the `new_` method that `EscapeAnalysisBasicBlockBuilder` inherits from `DelegatingBasicBlockBuilder` is called with the thread name that I captured in the first rule, log a message with the parameter and the value returned. This kind of trace logging is superior compared to the suggested approach, as it cuts down the amount of logging generated, hence speeding up its analysis, and can easily be tailored based on the situation.

One note: `traceln` just prints to the system out. This IMO is just fine, no need to get into the complexities of log files. You can just pipe the output to `tee`. Also, in containers system out is easier to grab than random generated log files that disappear when the container dies.

Having had a chat with @adinn, he had some interesting suggestions to make:

* Qbicc could come with a common suite of logging rules that we develop.
* We could split these rules into groups of high, medium, low and insane levels of debug messages.
* We could have rules factored or partitioned by functional area.
* These rules could be used as is, or they could be the starting point, with developers able to modify them to address a particular issue.

**Comment by galderz** [comment]
Oh one more thing: the Byteman proposal adds 0 new dependencies and can subtract existing logging dependencies from qbicc. This one Bela Ben would particularly love.

A clear downside would be the need to keep the rules in synch with code changes. If we use these rules to debug issues ourselves, I think we can quickly handle any outdates to the common rules provided.

**Comment by DanHeidinga** [comment]
Reflecting some of our zulip discussion here for posterity:

* Byteman sounds like a great approach for flexible logging during qbicc development.  As we develop qbicc, creating a library of byteman rules makes sense and avoids littering the code with logging.
* The original intention of #550 was for **runtime** trace of operations like `VMHelpers::initialize_class()` where we want to see when / if events have happened in the compiled program.
* qbicc doesn't fire ClassFileLoadHooks so byteman can't instrument qbicc's view of classes (ie: DefinedTypeDefinition/LoadedTypeDefinition).
* We should explore off-line instrumentation of classfiles.  Need to ask @adinn if byteman can be used in an off-line mode to modify classfiles on disk.

**Comment by dmlloyd** [comment]
Per call, closing. We can open a new issue for actual JFR support some time in the future.
